[package]
name = "vagus-platform-windows"
description = "Safe wrappers over the Windows APIs that Vagus collects data from."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
thiserror.workspace = true
windows-sys = { workspace = true, features = [
    "Wdk_System_SystemInformation",
    "Win32_Foundation",
    "Win32_System_WindowsProgramming",
] }

[lints]
workspace = true
